{
   "D" : {
      "files" : {
         "D" : {
            "/etc/cron.d/beta" : {
               "A" : "* * * * * root sleep 5"
            },
            "/etc/hostname" : {
               "N" : "beta",
               "O" : "alpha"
            },
            "/etc/hosts" : {
               "U" : "127.0.0.1    localhost"
            },
            "/etc/resolv.conf" : {
               "U" : "nameserver 8.8.8.8"
            }
         }
      },
      "fqdn" : {
         "N" : "beta.example.org",
         "O" : "alpha.example.org"
      },
      "mtime" : {
         "N" : "1462431002",
         "O" : "1462431001"
      }
   }
}
