Usage:
        nddiff [OPTIONS] <file1> <file2>

Options:
    --[no]colors
        On/Off colors for diff.

    --help|-h
        Print a help message and exit.

    --json
        Use JSON as diff format.

    --ignore <path>
        Ignore substructure. This path is used relatively to --path opt. May
        be used several times.

    --list-modules|-l
        Print list of available diff modules.

    --module|-m <name>
        Use specified diff module.

    --path <path>
        Define path to substructure to deal with. See detailed syntax
        description at <https://metacpan.org/pod/Struct::Path::PerlStyle>

    --[no]pretty
        On/Off pretty-print for JSON. Enabled by default.

    --quiet|-q
        Don't show diff, only exit code shows exists diff or not.

    --verbose|-v [int]
        Increase verbosity, max level - 4.

    --version|-V
        Print version and exit.

Examples:
    Simple diff:

        nddiff a.json b.json

