Usage:
        nddiff [OPTIONS] <file1> <file2>

Options:
    --[no]colors
        On/Off colors for diff.

    --help|-h
        Print a help message and exit.

    --list-modules|-l
        Print list of available diff modules.

    --module|-m <name>
        Use specified diff module.

    --verbose|-v [int]
        Increase verbosity, max level - 4.

    --version|-V
        Print version and exit.

Examples:
    Simple diff:

        nddiff a.json b.json

