Usage:
        ndmerge [OPTIONS]
        ndmerge [OPTIONS] <arguments>

Options:
    --dump-blame <file>
        Dump blame.

    --dump-rules <file>
        Dump merge rules.

    --dump-prereqs <file>
        Dump list of prerequisites from merge rules.

    --embed-rules <path>
        Embed rules into structure.

    --file|-f <file>
        File to merge, also is a rule delimiter (all other opts affect only
        cpecified file). May be used several times.

    --help|-h
        Print a help message and exit.

    --ignore <path>
        Skip specified structure parts. Positional: per-source. May be used
        several times.

    --load-rules|--rules <file>
        Load merge rules from specified file. May be used several times.

    --merge <path>
        Don't merge whole document, only specified parts. Paths '' or '{}'
        or '[]' means "whole" struct, use it as first merge target if whole
        struct must be merged and some parts merged with specific options.
        Positional: per-source. May be used several times.

    --style <L_OVERRIDE|R_OVERRIDE>
        Merge style. Positional: defines merge style per-process, per-source
        or per-merge according it's porition relatively to --file and
        --merge options.

        L_OVERRIDE, R_OVERRIDE
                Objects merged, lists overrided, left and right precedence.

        Default is R_OVERRIDE

    --verbose|-v [int]
        Increase verbosity, max level - 4.

    --version|-V
        Print version and exit.

Examples:
    Simply merge three files:

        ndmerge a.json b.json c.json

    Merge using rules, defined via opts:

        ndmerge \
            --file a.json \                      # define a file to merge with
                --ignore '{some}[0,3]{path}' \   # matched subsrtuctures in a.json will not be merged
            --file b.json \                      # new file name is also set a 'namespace' for other opts
                --merge '{in_list}[2]' \         # merge only specified parts
                --style 'L_OVERRIDE'             # with non default style
            --file c.json                        # here merge style again will be default (ie R_OVERRIDE)

    Merge using rules deined in file:

        ndmerge --rules rules.json               # rules may be saved to file by --dump-rules option

