[
   {
      "b" : {
         "files" : {
            "/etc/hostname" : "alpha",
            "/etc/hosts" : "127.0.0.1    localhost",
            "/etc/resolv.conf" : "nameserver 8.8.8.8"
         },
         "fqdn" : "alpha.example.org",
         "mtime" : 1462431001
      },
      "src" : "../alpha.json"
   },
   {
      "b" : {
         "files" : {
            "/etc/cron.d/beta" : "* * * * * root sleep 5"
         },
         "fqdn" : "beta.example.org",
         "mtime" : "1462431002"
      },
      "src" : "../beta.json"
   },
   {
      "b" : {
         "fqdn" : "alpha.example.org",
         "mtime" : "1462431001"
      },
      "src" : "../alpha.json"
   },
   {
      "b" : {
         "fqdn" : "beta.example.org",
         "mtime" : "1462431002"
      },
      "src" : "../beta.json"
   }
]
