{
   "__ndmerge__" : {
      "rules" : [
         {
            "src" : "../alpha.json"
         },
         {
            "merge" : [
               {
                  "path" : "{}"
               },
               {
                  "path" : "{\"fqdn\"}",
                  "style" : "R_OVERRIDE"
               },
               {
                  "path" : "{\"mtime\"}",
                  "style" : "R_OVERRIDE"
               }
            ],
            "src" : "../beta.json",
            "style" : "L_OVERRIDE"
         }
      ]
   },
   "files" : {
      "/etc/cron.d/beta" : "* * * * * root sleep 5",
      "/etc/hostname" : "alpha",
      "/etc/hosts" : "127.0.0.1    localhost",
      "/etc/resolv.conf" : "nameserver 8.8.8.8"
   },
   "fqdn" : "beta.example.org",
   "mtime" : 1462431002
}
