#!/usr/bin/env perl

use NDTools::NDPatch;
NDTools::NDPatch->run();

__END__

=head1 NAME

ndpatch - apply diff to a file

=head1 SYNOPSIS

    ndpatch [OPTIONS]
    ndpatch [OPTIONS] <file> [<patchfile>]

=head1 DESCRIPTION

Apply diff file to original one

=head1 OPTIONS

=over 4

=item B<--help|-h>

Print a help message and exit.

=item B<--verbose|-v> [int]

Increase verbosity, max level - 4.

=item B<--version|-V>

Print version and exit.

=back

=head1 EXAMPLES

Apply patch:

    ndpatch struct.json patch.json

=head1 EXIT STATUS

 0   No errors occured.
 1   Generic error code.
 2   I/O Error.
 8   Diff/patch related errors.

=head1 REPORTING BUGS

Report bugs to L<https://github.com/mr-mixas/NDTools/issues>

=head1 SEE ALSO

L<patch(1)>

L<nddiff(1)>, L<ndproc(1)>, L<ndquery(1)>

L<Struct::Diff>

=head1 LICENSE AND COPYRIGHT

Copyright 2016 Michael Samoglyadov C<< <mixas at cpan.org> >>.

This program is free software; you can redistribute it and/or modify it
under the terms of GNU General Public License 3 or later versions.
