=head1 NAME

ndtools - a set of command line tools aimed to help to deal with nested data
structures

=head1 SYNOPSIS

    nd* --help|--version
    nd* [OPTIONS] <arguments>

See exact list of options, examples and exit codes for each tool in it's man page

=head1 DESCRIPTION

JSON and YAML nowadays are everywhere and often requires quite complex
processing. This tools may solve some "pain in the neck" cases without writing
any code.

=head1 TOOLS

=over 4

=item nddiff

Diff tool, extendable by modules

=item ndmerge

Merge multiple documents, using rules

=item ndquery

Inspect structure or dump/modify it's parts

=back

=head1 REPORTING BUGS

Report bugs to L<https://github.com/mr-mixas/NDTools/issues>

=head1 SEE ALSO

L<nddiff(1)>, L<ndmerge(1)>, L<ndquery(1)>

L<jq(1)>, L<json(1)>
