Usage:
        ndquery [OPTIONS]
        ndquery [OPTIONS] <arguments>

Options:
    --depth|-d <int>
        Combined with --list allows to define how much levels must be listed

    --help|-h
        Print a help message and exit.

    --insert <file>
        Load data from file and insert to structire using path as a pointer.

    --list|-l
        List structure's paths

    --out-fmt <JSON|YAML>
        Output format selector. JSON used by default.

    --path|-p <string>
        Path in the structure to deal with.

    --verbose|-v [int]
        Increase verbosity, max level - 4.

    --version|-V
        Print version and exit.

Examples:
    Show as pretty printed canonical JSON:

        ndquery struct.json

    Get specified path from document:

        ndquery --path '{some}{path}[2]' struct.json

    List subpaths:

        ndquery --list --path '{some}{path}[2]' struct.json

